apiVersion: v1
kind: Service 
metadata:
  name: at-pods-lb-owasp-cheetsheets-nginx
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    # Loadbalance traffic across Pods matching this label selector
    app: atapp-owasp-cheetsheets-nginx
  ports: 
    - name: http
      port: 8081 # Service Port
      targetPort: 80 # Container Port

# # Create Service
# kubectl apply -f 03-pod-LoadBalancer-service.yml

# # List Service
# kubectl get svc

# # Access Application
# http://<Load-Balancer-Service-IP>
